### ISSUE TITLE
Mongodb config node error when deploying

### ISSUE THREAD

**Issue by vicary** [joeartsea/node-red-heroku#4]
This error was raised when I try to deploy the flow with a `node-red-node-mongodb` config node.

I have working instances in other distro, so this might be platform specific.

Here is the full error message.

```
MongoError: The dollar ($) prefixed field '$' in 'credentials.$' is not valid for storage.
    at Object.toError (/app/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /app/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
    at /app/node_modules/mongodb/lib/mongodb/db.js:1197:7
    at /app/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/app/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /app/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at MongoReply.parseBody (/app/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at .<anonymous> (/app/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
```

**Comment by thomasrabelo** [comment]
I just got the same error. :-(

**Comment by cavamora** [comment]
same here!!! anyone has a fix for this??

**Comment by joeartsea** [comment]
It worked if version of node-red was less than 0.14, Probably because the credentials were encrypted.
http://nodered.org/blog/2016/10/11/version-0-15-released

**Comment by joeartsea** [comment]
Added credentialSecret to setting.js.
```
credentialSecret: false
```
This error was also avoided in the latest version of Node-RED.

**Comment by cavamora** [comment]
perfect! worked like a charm. thanks!!
